apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: celery-exporter-servicemonitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: celery-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
